#!/bin/zsh
# $1 path/to/linux

set -e

linux=${1:a}
cd "${0:a:h}/.."

generate() {
    if [[ -e "$linux/$1" ]]; then
        scripts/extract-kconfigs --include-prefix=/generated/ -o generated "$linux" "$1"
    else
        mkdir -p generated/${1:h}
        echo '# not exists' > generated/$1
    fi
}

generate "init/Kconfig"
generate "arch/Kconfig"
for arch in x86 arm64; do
    generate "arch/$arch/Kconfig"
    generate "arch/$arch/Kconfig.debug"
done
generate "fs/Kconfig.binfmt"
generate "mm/Kconfig"
generate "net/Kconfig"
generate "drivers/Kconfig"
generate "fs/Kconfig"
generate "security/Kconfig"
generate "crypto/Kconfig"
generate "lib/Kconfig"
generate "lib/Kconfig.debug"
generate "distro/Kconfig"
